name: Build & Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Dockerfiles
      run: docker build -f Dockerfile .. -t carbon-http:latest --no-cache
